/*generator by gen reslit tools do not edit it!*/
export let reslist: Map<string, number> = new Map<string, number>([
    ["Texture/Cards/FangKuai/r1", 1],
    ["Texture/Cards/FangKuai/r2", 1],
    ["Texture/Cards/FangKuai/r3", 1],
    ["Texture/Cards/FangKuai/r4", 1],
    ["Texture/Cards/FangKuai/r5", 1],
    ["Texture/Cards/FangKuai/r6", 1],
    ["Texture/Cards/FangKuai/r7", 1],
    ["Texture/Cards/FangKuai/r8", 1],
    ["Texture/Cards/FangKuai/r9", 1],
    ["Texture/Cards/FangKuai/r10", 1],
    ["Texture/Cards/FangKuai/r11", 1],
    ["Texture/Cards/FangKuai/r12", 1],
    ["Texture/Cards/FangKuai/r13", 1],

    ["Texture/Cards/HeiTao/h1", 1],
    ["Texture/Cards/HeiTao/h2", 1],
    ["Texture/Cards/HeiTao/h3", 1],
    ["Texture/Cards/HeiTao/h4", 1],
    ["Texture/Cards/HeiTao/h5", 1],
    ["Texture/Cards/HeiTao/h6", 1],
    ["Texture/Cards/HeiTao/h7", 1],
    ["Texture/Cards/HeiTao/h8", 1],
    ["Texture/Cards/HeiTao/h9", 1],
    ["Texture/Cards/HeiTao/h10", 1],
    ["Texture/Cards/HeiTao/h11", 1],
    ["Texture/Cards/HeiTao/h12", 1],
    ["Texture/Cards/HeiTao/h13", 1],

    ["Texture/Cards/HongTao/d1", 1],
    ["Texture/Cards/HongTao/d2", 1],
    ["Texture/Cards/HongTao/d3", 1],
    ["Texture/Cards/HongTao/d4", 1],
    ["Texture/Cards/HongTao/d5", 1],
    ["Texture/Cards/HongTao/d6", 1],
    ["Texture/Cards/HongTao/d7", 1],
    ["Texture/Cards/HongTao/d8", 1],
    ["Texture/Cards/HongTao/d9", 1],
    ["Texture/Cards/HongTao/d10", 1],
    ["Texture/Cards/HongTao/d11", 1],
    ["Texture/Cards/HongTao/d12", 1],
    ["Texture/Cards/HongTao/d13", 1],

    ["Texture/Cards/MeiHua/b1", 1],
    ["Texture/Cards/MeiHua/b2", 1],
    ["Texture/Cards/MeiHua/b3", 1],
    ["Texture/Cards/MeiHua/b4", 1],
    ["Texture/Cards/MeiHua/b5", 1],
    ["Texture/Cards/MeiHua/b6", 1],
    ["Texture/Cards/MeiHua/b7", 1],
    ["Texture/Cards/MeiHua/b8", 1],
    ["Texture/Cards/MeiHua/b9", 1],
    ["Texture/Cards/MeiHua/b10", 1],
    ["Texture/Cards/MeiHua/b11", 1],
    ["Texture/Cards/MeiHua/b12", 1],
    ["Texture/Cards/MeiHua/b13", 1],
]);
